# Generated by Django 5.0.6 on 2024-06-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recorded_by',
        ),
    ]
