# Generated by Django 5.0.6 on 2024-07-01 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_event_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.action', verbose_name='事件'),
        ),
        migrations.AlterField(
            model_name='event',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.period', verbose_name='时段'),
        ),
        migrations.AlterField(
            model_name='event',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='bed_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.bed', verbose_name='床铺'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dorm_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.dorm', verbose_name='宿舍'),
        ),
        migrations.AlterField(
            model_name='student',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.flag', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.grade', verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
        migrations.CreateModel(
            name='Quantify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
    ]
