# Generated by Django 5.0.6 on 2024-07-01 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_total_score_alter_event_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantify',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.period', verbose_name='时段'),
        ),
    ]
