# Generated by Django 5.0.7 on 2024-08-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='total_score',
        ),
    ]
