# Generated by Django 5.0.7 on 2024-08-03 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_site_alter_customuser_options_alter_quantify_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
