# Generated by Django 5.0.7 on 2024-08-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_event_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user'},
        ),
        migrations.AlterModelOptions(
            name='quantify',
            options={'verbose_name': 'quantify'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Site'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default.jpg', upload_to='users/avatar/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
