# Generated by Django 5.0.7 on 2024-08-23 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_customuser_options_alter_quantify_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
