# Generated by Django 5.0.7 on 2024-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_event_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_pinyin',
            field=models.CharField(blank=True, max_length=100, verbose_name='姓名拼音'),
        ),
    ]
