# Generated by Django 5.2.5 on 2025-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_dorm_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
